server:
  port: 8080
  servlet:
    context-path: /

# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1：3306/intelligent-course-system?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: ""

mybatis-plus:
  type-aliases-package: com.zephyrtoria.pojo